const data = {
  products: [
    {
      name: 'Antique Chair',
      slug: 'antique-chair',
      category: 'Antique',
      image: '/images/1.jpg',
      price: 1200,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 10,
      description: 'This is a very famous antique chair.',
    },
    {
      name: 'Antique Book',
      slug: 'antique-book',
      category: 'Antique',
      image: '/images/2.jpg',
      price: 1125,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 10,
      description: 'This is a very famous antique book.',
    },
    {
      name: 'Antique Compass',
      slug: 'antique-compass',
      category: 'Antique',
      image: '/images/3.jpg',
      price: 3000,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 10,
      description: 'This is a very famous antique Compass.',
    },
    {
      name: 'Antique Cup',
      slug: 'antique-cup',
      category: 'Antique',
      image: '/images/4.jpg',
      price: 1200,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 20,
      description: 'This is a very famous antique cup.',
    },
    {
      name: 'Antique Premium Clock',
      slug: 'antique-premium-clock',
      category: 'Antique',
      image: '/images/5.jpg',
      price: 1900,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 10,
      description: 'This is a very famous antique premium clock.',
    },
    {
      name: 'Clock',
      slug: 'antique-clock',
      category: 'Antique',
      image: '/images/6.jpg',
      price: 2200,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 5,
      description: 'This is a very famous premium antique clock.',
    },
    {
      name: 'Antique Frame',
      slug: 'antique-frame',
      category: 'Antique',
      image: '/images/7.jpg',
      price: 1800,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 20,
      description: 'This is a very famous antique frame.',
    },
    {
      name: 'Antique Globe',
      slug: 'antique-globe',
      category: 'Antique',
      image: '/images/8.jpg',
      price: 1200,
      brand: 'Antique',
      rating: 5,
      numReviews: 8,
      countInStock: 20,
      description: 'This is a very famous antique globe.',
    },
  ],
};
export default data;
